spring:
  application:
    name: currency-exchange
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:currencydb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  retry:
    instances:
      sample-api:
        maxAttempts: 5
        waitDuration: 1s
        enableExponentialBackoff: true
  ratelimiter:
    instances:
      default:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
  bulkhead:
    instances:
      default:
        maxConcurrentCalls: 10
      sample-api:
        maxConcurrentCalls: 10
